name: Conversations with Shanghai Cabbies
favicon: null
layout_spectrum: 0.561955827055499
typography_spectrum: 0.5367724697571248
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.34333859756588936
  lightness: 0.9651724847499281
  saturation: 0.540873717982322
  rhythmicContrast: 0.4593952929135412
purpose: []
